### ISSUE TITLE
Application won't open

### ISSUE THREAD

**Issue by ionreflex** [pavelsof/mobile-wormhole#1]
version 0.1.2
Pixel 3
Android 10 (QQ2A.200501.001.B2)

Behavior: show splash screen than stop! Not sure if I can debug this...

Here to help because this app would be awesome!

**Comment by pavelsof** [comment]
Thank you for opening the first issue and for the nice words :)

I will try to get my hands on an Android 10 device these days (I do not happen to have one around). On the emulator the app seems to work, but either this does not mean much or I am not configuring it right.

**Comment by ionreflex** [comment]
Hi Pavel, I'm looking at a way to collect debug data on my phone that could help, as this is something I've never done; I'll keep you informed

-|-

**Comment by leonardospina** [comment]
Android 10 here, Samsung A9, same issue, splash screen appears and the disappears. No error messages unfortunately!
Thanks for the awesome app!

**Comment by pavelsof** [comment]
I managed to reproduce it, somehow the release apk does not include the gradle dependency specified in `buildozer.spec` while the debug apk does (and it works on the same device on which the release apk fails). I will try to fix it over the weekend (:

**Comment by leonardospina** [comment]
eheh thank you for your very good job

**Comment by pavelsof** [comment]
Just released a new version in the beta channel (v0.1.4) that seems to work. At the end of the day, the fix turned out to be `rm -rf .buildozer` and building the apk files again..

**Comment by smarnv** [comment]
Thanks for the fix. The app doesn't crash like this anymore. :slightly_smiling_face:

**Comment by pavelsof** [comment]
Please feel free to re-open the issue if it has not been fixed with the last version on Google Play. Thank you all once again :)
