### ISSUE TITLE
Relase on f-droid.org

### ISSUE THREAD

**Issue by muelli** [pavelsof/mobile-wormhole#3]
It'd be cool to have this wormhole client on F-Droid, so that people who care about Free Software can obtain it.
The process is relatively easy and once it's set up,
It seems that there are other projects making use of Kivy, e.g. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.github.andremiras.etheroll.yml so it should be possible to add this app, too.

**Comment by pavelsof** [comment]
Thank you for opening this issue. I also use F-Droid on my private phone and would be happy to have the app published there. However, in spite of there being other Kivy apps on F-Droid, this one fails to build; here is the merge request:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7881

Of course, any help with fixing whatever is wrong is welcome!

**Comment by IzzySoft** [comment]
Welcome to F-Droid! Your app was just published with the last batch yesterday \o/ Now that it's there, I'd usually remove it from my repo after a decent overlap (7..10 days) unless explicitly requested to keep it (see [here for some background](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)). So please let me know your stance :wink:

**Comment by pavelsof** [comment]
@IzzySoft, thank you for all the help with getting this app on F-Droid!

I do not mind uploading a signed APK with each GitHub release, so why not keep it on your repo as well :)

**Comment by IzzySoft** [comment]
> thank you for all the help with getting this app on F-Droid!

Gladly done!

> why not keep it on your repo as well

Size constraints? :see_no_evil: Thanks, keeping it for now (and having marked it such). But once it exceeds the size limit (30M) I might need to reconsider. Hm, maybe compressing that `private.mp3`?

Ouch, what is that? That's actually a `.tar.gz` full of binaries? Can you explain before I need to raise a red flag?

**Comment by pavelsof** [comment]
Oh, yes, this is how Kivy/Buildozer works. I do not know why it has an .mp3 extension when it is not an .mp3 file but, as you said, an archive. It is not explained anywhere in the docs, when I first came across it, I also thought there is something fishy, but then I made a hello world Kivy app and it also had this fake mp3.. :smiley:

**Comment by pavelsof** [comment]
By the way, do you know why this page returns 404:
https://f-droid.org/en/packages/com.pavelsof.wormhole

**Comment by IzzySoft** [comment]
If one isn't used to that, it can give quite an adrenaline kick :rofl: Luckily, 2 of our team members quickly educated me. And there I thought we could squeeze some juice by reducing the bitrate of that tarball :see_no_evil:

And well, website is always a bit behind (updated asynchronously) – sometimes unfortunately a lot. So if you want to confirm whether an update has arrived, better use my repo browser. It covers several repos – so you could look up your app in my repo and simply add `?repo=main` to the URL to see its counter-part. If it shows up, it's in the index (delay should rarely be more than 6h with my repo browser, as it checks 4 times a day). [Here you go](https://apt.izzysoft.de/fdroid/index/apk/com.pavelsof.wormhole?repo=main), it's listed – take away the "suffix", and see it in mine. If you want to update your "badge list", [find the badge for my repo here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smile:
