### ISSUE TITLE
Ability to configure a wormhole server and a relay server

### ISSUE THREAD

**Issue by vu3rdd** [pavelsof/mobile-wormhole#4]
It looks like the wormhole server and the relay server configuration is baked into the app. It would be nice to make these configurable.

**Comment by pavelsof** [comment]
Done! Added a config screen where the server URLs can be changed; will try to make a new release these days.

**Comment by vu3rdd** [comment]
Thank you!

**Comment by pavelsof** [comment]
Included in the new version (0.2.0) :upside_down_face:
