### ISSUE TITLE
Showing the progress of the transfer could be nice

### ISSUE THREAD

**Issue by wdbm** [pavelsof/mobile-wormhole#5]
Just as for the case of the terminal interface to Magic Wormhole, a representation of the transmission progress (percentage, for example) could be nice.

**Comment by pavelsof** [comment]
Done! Now the user can see how many bytes have been transferred; I will try to make a new release these days.

**Comment by pavelsof** [comment]
Included in the new version (0.2.0) :slightly_smiling_face:
