### ISSUE TITLE
Keep screen awake

### ISSUE THREAD

**Issue by rixx** [pavelsof/mobile-wormhole#8]
First off: Thank you for building this! Having an easy way to transfer large files to my phone is amazing and I love it.

Do you think you could add a way to keep the screen from locking? The app doesn't continue running while in the background (which is fine imo), but it would be nice to leave the phone somewhere and come back an hour later when all files are downloaded. Currently it will just stop once the screen goes dark.

**Comment by pavelsof** [comment]
Thank you for the nice words! :upside_down_face: 

This makes sense, I will try to do it this weekend.

**Comment by pavelsof** [comment]
Done! The app will now always keep the screen on and the file transfers do not get interrupted. A possible downside is that the screen will be on regardless of whether a file is being transferred or not; but I guess this is OK.

Will make a release today (:
